[project]
name = "scentityexporter"
version = "1.0.0"
description = "A tool to export Star Citizen Entities to view them in blender"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "customtkinter>=5.2.2",
    "line-profiler>=4.2.0",
    "pyinstaller>=6.13.0",
]
